### ISSUE TITLE
Fix the search bar

### ISSUE THREAD

**Issue by ayuxy027** [ayuxy027/Topic#1]
### End Goal
<img width="874" alt="Screenshot 2024-03-09 at 8 15 37 PM" src="https://github.com/ayuxy027/Topic/assets/144288354/fa897363-fb23-414b-80c0-c79e60c06439">

### meanwhile looks like this --
<img width="893" alt="Screenshot 2024-03-10 at 3 31 36 PM" src="https://github.com/ayuxy027/Topic/assets/144288354/9f88a7f4-4677-46e8-a833-0a1bef71e0ed">

Check the tailwind.config file to see the color variables created for direct usage, add hover effect accordingly

**Comment by Fabi-ruc** [comment]
Hi, I would like to help with this issue.
I'd be lovely if you could assign me, in case you could use my help :)

**Comment by ayuxy027** [comment]
> Hi, I would like to help with this issue. I'd be lovely if you could assign me, in case you could use my help :)

# Project Assignment

Hey,

Sure, I would love to assign this task to you. Please make sure to follow the instructions below:

## Instructions

1. Run the following command:

   ```bash
   npx tailwindcss -i ./src/input.css -o ./public/output.css --watch
   
   This command will watch for changes in the input.css file located in the ./src directory and generate the corresponding output in the ./public directory.

2. Do not change HTML IDs.

3. Refer to the tailwind.config.js file for colour configurations. Utilize these colours in your implementation right away!

4. Remember to add comments describing the changes in detail :)

Comments are added to the index.html so you can cruise easily in the project

Feel free to reach out if you have any questions or need further clarification.

**Comment by Fabi-ruc** [comment]
Thanks for the help with setting up the Contribution :)

I have tried my best to implement the End goal, with the current result looking as follows:
![grafik](https://github.com/ayuxy027/Topic/assets/74418232/5d0079c4-3509-4f5f-9d7f-59d9915069e4)

with a hover and focus effect for the search bar turning the background white:
![grafik](https://github.com/ayuxy027/Topic/assets/74418232/56948709-972e-4e16-b312-9fa48dd0794f)

Are there any more effects that should be added or general improvements?

**Comment by ayuxy027** [comment]
> Thanks for the help with setting up the Contribution :)
> 
> 
> 
> I have tried my best to implement the End goal, with the current result looking as follows:
> 
> ![grafik](https://github.com/ayuxy027/Topic/assets/74418232/5d0079c4-3509-4f5f-9d7f-59d9915069e4)
> 
> 
> 
> with a hover and focus effect for the search bar turning the background white:
> 
> ![grafik](https://github.com/ayuxy027/Topic/assets/74418232/56948709-972e-4e16-b312-9fa48dd0794f)
> 
> 
> 
> Are there any more effects that should be added or general improvements?

Hey,
Thank you for contributing and fixing the search bar
You can raise a PR to merge your contribution now 🚀
If you want to add something, you can set up the card section in the project which is in the lower Div.
For reference of the end goal do check the assets folder and then page1top img.
Thank you again :)

**Comment by ayuxy027** [comment]
> Thanks for the help with setting up the Contribution :)
> 
> 
> 
> I have tried my best to implement the End goal, with the current result looking as follows:
> 
> ![grafik](https://github.com/ayuxy027/Topic/assets/74418232/5d0079c4-3509-4f5f-9d7f-59d9915069e4)
> 
> 
> 
> with a hover and focus effect for the search bar turning the background white:
> 
> ![grafik](https://github.com/ayuxy027/Topic/assets/74418232/56948709-972e-4e16-b312-9fa48dd0794f)
> 
> 
> 
> Are there any more effects that should be added or general improvements?

Hey,
Thank you for contributing and fixing the search bar
You can raise a PR to merge your contribution now 🚀
If you want to add something, you can set up the card section in the project which is in the lower Div.
For reference of the end goal do check the assets folder and then page1top img.
Thank you again :)

**Comment by ayuxy027** [comment]
> Thanks for the help with setting up the Contribution :)
> 
> 
> 
> I have tried my best to implement the End goal, with the current result looking as follows:
> 
> ![grafik](https://github.com/ayuxy027/Topic/assets/74418232/5d0079c4-3509-4f5f-9d7f-59d9915069e4)
> 
> 
> 
> with a hover and focus effect for the search bar turning the background white:
> 
> ![grafik](https://github.com/ayuxy027/Topic/assets/74418232/56948709-972e-4e16-b312-9fa48dd0794f)
> 
> 
> 
> Are there any more effects that should be added or general improvements?

Hey,
Thank you for contributing and fixing the search bar
You can raise a PR to merge your contribution now 🚀
If you want to add something, you can set up the card section in the project which is in the lower Div.
For reference of the end goal do check the assets folder and then page1top img.
Thank you again :)

**Comment by Fabi-ruc** [comment]
I'll try my hand at those Card sections then :)

**Comment by ayuxy027** [comment]
> I'll try my hand at those Card sections then :)

**Hey, if you are done with the cards section make sure to raise the PR asap so that we can proceed further,** 

**Thank you!**

**Comment by Fabi-ruc** [comment]
Sorry for taking a while, I have a solution though it could probably still be improved upon by quite a bit, but sadly I'm not entirely sure how.

The following is my current result:
![grafik](https://github.com/ayuxy027/Topic/assets/74418232/330f333a-49f0-4277-8ba2-8e049a60b114)

I will raise a pull request immediately :)

**Comment by ayuxy027** [comment]
> Sorry for taking a while, I have a solution though it could probably still be improved upon by quite a bit, but sadly I'm not entirely sure how.
> 
> The following is my current result: ![grafik](https://private-user-images.githubusercontent.com/74418232/312210654-330f333a-49f0-4277-8ba2-8e049a60b114.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAyODg0MzMsIm5iZiI6MTcxMDI4ODEzMywicGF0aCI6Ii83NDQxODIzMi8zMTIyMTA2NTQtMzMwZjMzM2EtNDlmMC00Mjc3LThiYTItOGUwNDlhNjBiMTE0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzEzVDAwMDIxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdjYWY0OWE5OTFmNjJjMWRiYTQ4NmY0ZGNjZDQ4YWNhZTVlODM3OGMyNDU4MGE1MzNiMzJjZDIyNjBiNDQwOTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.u8L94z1WU_6Kn5hBNwmSe-v3pRjscVY6h3g6anXUBhQ)
> 
> I will raise a pull request immediately :)


Thank you for your valuable time and contributions! 

If you're interested in helping out further in frontend projects, do take a look at my other project, Green Era. 

I've opened an issue there as well.
